export default [
  {
    referencia: 'A13725478',
    descripcion: 'Camisa de manga corta, de cuadros color naranja.',
    url: 'http://www.elcorteingles.es/moda/A13725478-camisa-de-hombre-de-cuadros',
    genero: 'Hombre',
    categoria: 'Camisas',
    marca: 'Pertegaz',
    precio: 65,
  },
  {
    referencia: 'A14815772',
    descripcion: 'Vestido corto con estampado multicolor.',
    url: 'http://www.elcorteingles.es/moda/A14815772-vestido',
    genero: 'Mujer',
    categoria: 'Vestidos',
    marca: 'Fórmula Joven',
    precio: 39.95,
  },
  {
    referencia: 'A13490757',
    descripcion: 'Pantalón tipo chino en color beige.',
    url: 'http://www.elcorteingles.es/moda/A13490757-pantalon-de-hombre',
    genero: 'Hombre',
    categoria: 'Pantalones',
    marca: 'Dockers',
    precio: 96,
  },
  {
    referencia: 'A12774586',
    descripcion: 'Leggin básico en color kaki.',
    url: 'http://www.elcorteingles.es/moda/A12774586-leggin-de-mujer',
    genero: 'Mujer',
    categoria: 'Pantalones',
    marca: 'Easy Wear',
    precio: 7.95,
  },
  {
    referencia: 'A14536494',
    descripcion: 'Zapatillas elaboradas en tejido con base de algodón.',
    url: 'http://www.elcorteingles.es/moda/A14536494-zapatillas-de-lona-de-hombre',
    genero: 'Hombre',
    categoria: 'Zapatos',
    marca: 'Camper',
    precio: 80,
  },
  {
    referencia: 'A13380785',
    descripcion: 'Sandalias de tacón elaboradas en piel en color beige.',
    url: 'http://www.elcorteingles.es/moda/A13380785-sandalias-de-mujer',
    genero: 'Mujer',
    categoria: 'Zapatos',
    marca: 'Hugo Boss',
    precio: 399,
  },
];
